name: Android CI

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Install packages using apt-get
        run: |
          sudo apt-get update
          sudo apt-get install -y zipalign

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install build tools
        run: |
          sdkmanager "build-tools;34.0.0"
          echo "${ANDROID_HOME}/build-tools/34.0.0" >> $GITHUB_PATH

      - name: Install Dependencies
        run: npm install && npm run build

      - name: Sync Capacitor Plugins
        run: npx cap sync

      - name: Decode Keystore
        run: |
          echo ${{ secrets.KEYSTORE_BASE64 }} | base64 -d > $GITHUB_WORKSPACE/keystore.jks

      - name: Build Android APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Align APK
        run: |
          cd android/app/build/outputs/apk/release
          zipalign -v -p 4 app-release-unsigned.apk ludditelauncher-aligned.apk

      - name: Sign APK
        run: |
          cd android/app/build/outputs/apk/release
          apksigner sign --ks $GITHUB_WORKSPACE/keystore.jks \
            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --ks-key-alias ${{ secrets.KEY_ALIAS }} \
            --key-pass pass:${{ secrets.KEY_PASSWORD }} \
            ludditelauncher-aligned.apk

      - name: Verify Signed APK
        run: |
          cd android/app/build/outputs/apk/release
          apksigner verify ludditelauncher-aligned.apk

      - name: Prepare Version Variables
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"   # e.g., "v1.0.0"
          VERSION=${TAG_NAME#v}                  # strip leading "v", result = "1.0.0"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release
        with:
          files: android/app/build/outputs/apk/release/ludditelauncher-aligned.apk
          name: "LudditeLauncher ${{ env.VERSION }}"
          tag_name: ${{ github.ref_name }}

      - name: Upload APK to Infomaniak
        uses: Noelware/s3-action@2.2.7
        with:
          files: android/app/build/outputs/apk/release/ludditelauncher-aligned.apk
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # This was incorrect in your original file
          aws-endpoint: ${{ secrets.S3_ENDPOINT_URL }}
          bucket: ${{ secrets.S3_BUCKET_NAME }}
          aws-region: 'default-region' # Add this parameter (required for most S3 actions)
