name: Luddite Launcher CI

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Install build tools
        run: |
          sdkmanager "build-tools;34.0.0"
          echo "${ANDROID_HOME}/build-tools/34.0.0" >> $GITHUB_PATH

      - name: Install Dependencies
        run: npm install

      - name: Generate environment file with API key
        run: |
          echo "export const environment = {" > src/environments/environment.prod.ts
          echo "  production: true," >> src/environments/environment.prod.ts
          echo "  apiKey: '${{ secrets.API_KEY }}'," >> src/environments/environment.prod.ts
          echo "};" >> src/environments/environment.prod.ts

      - name: Build Angular App
        run: npm run build

      - name: Sync Capacitor Plugins
        run: npx cap sync

      - name: Decode Keystore
        run: |
          echo ${{ secrets.KEYSTORE_BASE64 }} | base64 -d > $GITHUB_WORKSPACE/keystore.jks

      - name: Build Android APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Align APK
        run: |
          cd android/app/build/outputs/apk/release
          zipalign -v -p 4 app-release-unsigned.apk ludditelauncher-aligned.apk

      - name: Sign APK
        run: |
          cd android/app/build/outputs/apk/release
          apksigner sign --ks $GITHUB_WORKSPACE/keystore.jks \
            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --ks-key-alias ${{ secrets.KEY_ALIAS }} \
            --key-pass pass:${{ secrets.KEY_PASSWORD }} \
            ludditelauncher-aligned.apk

      - name: Verify Signed APK
        run: |
          cd android/app/build/outputs/apk/release
          apksigner verify ludditelauncher-aligned.apk

      - name: Prepare Version Variables
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"   # e.g., "v1.0.0"
          VERSION=${TAG_NAME#v}                  # strip leading "v", result = "1.0.0"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          # Only on tag releases, update README with specific version info
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            echo "RELEASE_TAG=true" >> $GITHUB_ENV
          else
            echo "RELEASE_TAG=false" >> $GITHUB_ENV
          fi

      - name: Create GitHub Release
        if: env.RELEASE_TAG == 'true'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            android/app/build/outputs/apk/release/ludditelauncher-aligned.apk
            docs/LauncherDocumentation.pdf
          name: "LudditeLauncher ${{ env.VERSION }}"
          tag_name: ${{ github.ref_name }}
