name: Android CI

on:
  push:
    branches: ["main"]
    tags:
      - "*"
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: "21"

      - name: Install packages using apt-get
        run: |
          sudo apt-get update
          sudo apt-get install -y zipalign

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install build tools
        run: |
          sdkmanager "build-tools;34.0.0"
          echo "${ANDROID_HOME}/build-tools/34.0.0" >> $GITHUB_PATH

      - name: Install Dependencies
        run: npm install && npm run build

      - name: Sync Capacitor Plugins
        run: npx cap sync

      - name: Decode Keystore
        run: |
          echo ${{ secrets.KEYSTORE_BASE64 }} | base64 -d > $GITHUB_WORKSPACE/keystore.jks
          ls -la $GITHUB_WORKSPACE

      - name: Build Android APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Align APK
        run: |
          cd android/app/build/outputs/apk/release
          zipalign -v -p 4 app-release-unsigned.apk ludditelauncher-aligned.apk

      - name: Sign APK
        run: |
          cd android/app/build/outputs/apk/release
          apksigner sign --ks $GITHUB_WORKSPACE/keystore.jks \
            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --ks-key-alias ${{ secrets.KEY_ALIAS }} \
            --key-pass pass:${{ secrets.KEY_PASSWORD }} \
            ludditelauncher-aligned.apk

      - name: Verify Signed APK
        run: |
          cd android/app/build/outputs/apk/release
          apksigner verify ludditelauncher-aligned.apk

      - name: Create GitHub Release (Only on Tag)
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: android/app/build/outputs/apk/release/ludditelauncher-aligned.apk
