name: GitHub Pages Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set GitHub Token
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          echo "GH_TOKEN=${{ github.token }}" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Mermaid CLI
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Find and convert Mermaid diagrams
        run: |
          # Create a directory for the generated images if it doesn't exist
          mkdir -p Doc/images/mermaid

          # Find all .adoc files in the Doc directory
          find Doc -name "*.adoc" -type f | while read file; do
            echo "Processing $file"

            # Extract Mermaid diagrams from the file and convert them to PNG
            # This extracts content between [mermaid] and [/mermaid] tags
            grep -n "\[mermaid\]" "$file" | while read -r mermaid_line; do
              line_num=$(echo "$mermaid_line" | cut -d: -f1)

              # Get the ending line number
              end_line_num=$(tail -n +$line_num "$file" | grep -n "\[/mermaid\]" | head -1 | cut -d: -f1)
              end_line_num=$((line_num + end_line_num - 1))

              # Extract the diagram content
              diagram_content=$(sed -n "$((line_num+1)),$((end_line_num-1))p" "$file")

              # Generate a unique filename based on file and line number
              diagram_filename="mermaid_$(basename "$file" .adoc)_$line_num.png"

              # Write the diagram to a temporary file
              echo "$diagram_content" > temp_diagram.mmd

              # Convert to PNG using mmdc
              mmdc -i temp_diagram.mmd -o "Doc/images/mermaid/$diagram_filename" -t dark

              # Replace the Mermaid block with an image include in the file
              sed -i "${line_num}s/\[mermaid\]/image::images\/mermaid\/$diagram_filename\[\]/" "$file"
              sed -i "${end_line_num}d" "$file"
              for (( i=line_num+1; i<end_line_num; i++ )); do
                sed -i "$((line_num+1))d" "$file"
              done
            done
          done

          # Clean up
          rm -f temp_diagram.mmd

      - name: asciidoctor-ghpages
        uses: manoelcampos/asciidoctor-ghpages-action@v2.3.0
        with:
          pdf_build: true
          source_dir: Doc/
