name: GitHub Pages Publish


on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: asciidoctor-ghpages
        uses: manoelcampos/asciidoctor-ghpages-action@v2.3.0
        with:
          pdf_build: true
          # asciidoctor_params: --attribute=nofooter
          # adoc_file_ext: .ascii # default is .adoc
          source_dir: Doc/ # default is .
          # slides_build: true
          # pre_build:
          # post_build:
