name: GitHub Pages Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set GitHub Token
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          echo "GH_TOKEN=${{ github.token }}" >> $GITHUB_ENV

      - name: Extract and convert Mermaid diagrams
        run: |
          # Create directories
          mkdir -p Doc/images/mermaid

          # Find all .adoc files in the Doc directory
          find Doc -name "*.adoc" -type f | while read file; do
            echo "Processing $file"

            # Extract Mermaid diagrams from the file
            grep -n "\[mermaid\]" "$file" | while read -r mermaid_line; do
              line_num=$(echo "$mermaid_line" | cut -d: -f1)

              # Get the ending line number
              end_line_num=$(tail -n +$line_num "$file" | grep -n "\[/mermaid\]" | head -1 | cut -d: -f1)
              if [ -z "$end_line_num" ]; then
                echo "Warning: Could not find closing [/mermaid] tag for diagram at line $line_num in $file"
                continue
              fi
              end_line_num=$((line_num + end_line_num - 1))

              # Extract the diagram content
              diagram_content=$(sed -n "$((line_num+1)),$((end_line_num-1))p" "$file")

              # Generate a unique filename based on file and line number
              diagram_basename="mermaid_$(basename "$file" .adoc)_$line_num"

              # Write the diagram to a temporary file
              echo "$diagram_content" > "${diagram_basename}.mmd"

              echo "Converting $diagram_basename.mmd to PNG"

              # Use Docker to convert Mermaid to PNG
              docker run --rm -v $(pwd):/data minlag/mermaid-cli:latest -i /data/${diagram_basename}.mmd -o /data/Doc/images/mermaid/${diagram_basename}.png -t dark

              if [ -f "Doc/images/mermaid/${diagram_basename}.png" ]; then
                echo "Successfully converted diagram to PNG"

                # Replace the Mermaid block with an image include
                sed -i "${line_num}s/\[mermaid\]/image::images\/mermaid\/${diagram_basename}.png\[\]/" "$file"
                sed -i "${end_line_num}d" "$file"

                # Delete the diagram content lines
                for (( i=line_num+1; i<end_line_num; i++ )); do
                  sed -i "$((line_num+1))d" "$file"
                done

                # Clean up the temporary file
                rm "${diagram_basename}.mmd"
              else
                echo "Failed to convert diagram to PNG"
              fi
            done
          done

      - name: asciidoctor-ghpages
        uses: manoelcampos/asciidoctor-ghpages-action@v2.3.0
        with:
          pdf_build: true
          source_dir: Doc/
